In [8]:
#slicing:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[2:6]
print(slice1)

[3 4 5 6]


In [9]:
#Slicing: With step size of two
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice1=arr[::2]
print(slice1)

[1 3 5 7 9]


In [12]:
#Reversing:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
reversed=arr[::-1]
print(reversed)

[9 8 7 6 5 4 3 2 1]


In [14]:
#Slicing multi dimensional array:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[8,5,9,2]])
#slice rows from 0 to 2 column 1 to 3:
subarray=arr[0:2,1:3]
print(subarray)

[[2 3]
 [6 7]]


In [17]:
#Extracting from array:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[8,5,9,2]])
#slice rows from 0 to 2 column 1 to 3:
subrow=arr[1:2]
subcol=arr[:,0]
print(subrow)
print(subcol)

[[5 6 7 8]]
[1 5 8]


In [21]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[8,5,9,2]])
#slice rows from 0 to 2 column 1 to 3:
subrow=arr[0,0]
subcol=arr[1,2]
print(subrow)
print(subcol)

1
7


In [22]:
#Indexing techniques:

import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[1])

20


In [23]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[-1])

50


In [24]:
#Subset indexing:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[1:4])



[20 30 40]


In [25]:
#Index elements that meets the specific condition:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr>25)



[False False  True  True  True]


In [26]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [27]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [28]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [33]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
result=np.split(arr1,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [34]:
import numpy as np
arr1=np.array([1,23,4,5,6])
result=np.array_split(arr1,3)
print(result)

[array([ 1, 23]), array([4, 5]), array([6])]
