In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [4]:
import numpy as np
b=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",b)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:\n",d)


 Random value:
 [[0.35507195 0.81209456 0.8294121 ]
 [0.77540669 0.63444027 0.34330152]
 [0.32895178 0.86875831 0.01788786]]


In [8]:
import numpy  as np
e=np.arange(0,100,5)
print("\n Range value:\n",e)


 Range value:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape((4,3))
print("\n Original array:\n",arr)
print("\n Reshaped array [4,3]:\n", newarr)


 Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped array [4,3]:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
#program 7.1
import numpy as np
c=np.zeros((5,3))
print("\n Array with all zeros\n",c)

#program 7.2
import numpy as rnp
r=rnp.random.random((5,3))
print("\n Array with random values/n",r)
print("\n No of dimensions:",r.ndim)
print("\n Array element type:",r.dtype)

#program7.3
import numpy as snp
s=snp.arange(0,105,5)
print("\n Strip size array \n",s)

#program7.4
arr=rnp.array([[1,2,3],[5,6,7],[9,10,11],[13,14,15],[17,18,19]])
newarr=arr.reshape(3,5)
print("\n Reshaped array\n",newarr)


 Array with all zeros
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Array with random values/n [[5.06413568e-01 8.23798998e-01 3.81504661e-01]
 [5.60748667e-04 9.23313449e-01 7.96410426e-01]
 [8.43010971e-01 6.00633537e-02 2.97193028e-01]
 [6.16734358e-02 6.23560050e-01 6.35022809e-01]
 [6.64059188e-01 4.73052420e-01 8.68292112e-02]]

 No of dimensions: 2

 Array element type: float64

 Strip size array 
 [  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]

 Reshaped array
 [[ 1  2  3  5  6]
 [ 7  9 10 11 13]
 [14 15 17 18 19]]


#program8
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
flat=arr.flatten()
print("Flattened array;\n",flat)

In [20]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n No. of dimensions:",arr.ndim)


 No. of dimensions: 2


In [9]:
import numpy as a
arr=a.array([[1,2,3],[1,2,3]])
newtype=arr.astype("f")
print("\n convert array element :\n",newtype)
print("convert array :",newtype.dtype)
size=len(arr)
print("\n size of array:",arr.size)


 convert array element :
 [[1. 2. 3.]
 [1. 2. 3.]]
convert array : float32

 size of array: 6
